services:
  - type: web
    name: campus-market
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.22.1
    plan: free
